[package]
name = "proto-types"
version = "0.1.0"
edition = "2024"

[lib]
name="proto_types"

[dependencies]
prost = "0.14.1"
bytes = "1.11.0"
tonic = "0.14.2"
tonic-prost = "0.14.2"
[build-dependencies]
tonic-prost-build = "0.14.2"



[features]
default = []

ingest = []

radar = []
